### ISSUE TITLE
CodeQL does not work

### ISSUE THREAD

**Issue by zhangcs** [OpenCAEPlus/OpenCAEPoro#10]
### Describe the bug

cmake failed during auto-build

FASP could not be found. Check FASP DIR. (missing: FASP LIBRARIES FASP INCLUDE DIRS)
INFO: FASP was requested but not found!
INFO: Going to try download and install from git repo
CMake Error at _lgtm build dir/ deps/fasp-src/CMakeLists.txt:49 (string):
string sub-command STRIP requires two arguments.
FAP library installation dir: /home/runner/work/OpenCAEPoro/OpenCAEPoro/_lgtmbuilddir/deps/fasp-src/lib
FAP headers installation dir: /home/runner/work/OpenCAPoro/OpenCAEPoro/_lgtmbuilddir/_deps/fasp-src/include
Set build type to Release configuration
Set build type to Release configuration
Configuring incomplete, errors occurred!

### Reproduction

N/A

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Read the [docs](https://porous.opencaeplus.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by billcxx** [comment]
fixed with 390efd7913fd8571acd47c6fddb9398bcf34cfe1 and 6a84bdc3fc4a0d2445f9703af1c83ee8a128d62c

**Comment by zhangcs** [comment]
Works now
