### ISSUE TITLE
Build failed on mac oxs g++ 12.2 and xcode 14.0

### ISSUE THREAD

**Issue by zhangcs** [OpenCAEPlus/OpenCAEPoro#13]
### Describe the bug

Link failed with g++ and xcode 14.0.

0  0x10033bffa  __assert_rtn + 139
1  0x10019429d  mach_o::relocatable::Parser<arm64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x10016031f  mach_o::relocatable::Parser<arm64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x1001b57b4  archive::File<arm64>::makeObjectFileForMember(archive::File<arm64>::Entry const*) const + 1268
4  0x1001b4e3b  archive::File<arm64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
5  0x1001abd67  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 391
6  0x1001d6c8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
7  0x1001d9fa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
8  0x7ff81bbfba77  _dispatch_client_callout2 + 8
9  0x7ff81bc0d4e1  _dispatch_apply_invoke + 213
10  0x7ff81bbfba44  _dispatch_client_callout + 8
11  0x7ff81bc0b7f6  _dispatch_root_queue_drain + 683
12  0x7ff81bc0be4d  _dispatch_worker_thread2 + 160
13  0x7ff81bd77c9d  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/testOpenCAEPoro-2022-10-27-175937.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status

Wait for the updated version of Xcode.

### Reproduction

Xcode 14 on different macOS will generate this link error

### Expected behavior

N/A

### System Info

```shell
OSX, GNU+Xcode CMT 14.0
```

### Validations

- [X] Read the [docs](https://porous.opencaeplus.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zhangcs** [comment]
This problem still happens with CMT 14.1.

**Comment by billcxx** [comment]
@zhangcs Which g++ is the program using? On my computer the default g++ is at /usr/bin/g++, which also fails when I compile OpenCAXPlusSDK (the same program works on linux with gnu). This /usr/bin/g++ is not the homebrew installed one. To make OpenCAXPlusSDK work on mac with gnu, I have to specify using gcc-12 and g++-12

**Comment by zhangcs** [comment]
@billcxx I used g++12 in homebrew (on ARM M1 and intel x86 macbooks).

**Comment by zhangcs** [comment]
This problem now disappear with Xcode 14.1 and g++ 12.2.0.
