### ISSUE TITLE
网页链接仍指向老的git repo

### ISSUE THREAD

**Issue by zhangcs** [OpenCAEPlus/OpenCAEPoro#3]
### Describe the bug

https://porous.opencaeplus.org/ 里的一些链接和版本信息仍指向老版本

### Reproduction

NA

### Expected behavior

NA

### System Info

```shell
NA
```

### Validations

- [X] Read the [docs](https://faspdevteam.github.io/OpenCAEPoro).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by billcxx** [comment]
今天晚上我来更新

**Comment by billcxx** [comment]
除了 #5 中的修正

> [cbcdc03](https://github.com/OpenCAEPlus/OpenCAEPoro/commit/cbcdc03cc4c22fd62525c68dbbf941284f84add5) 之前问题是虽然action显示成功，但如果你打开具体的build doc那里，能看到其实是有错误的。 所以判断doc是否build成功要看最终有没有自动提交一个"update dist.zip"的commit，如果有就是build 成功，如果没有说明其实没有build 成功。 修正了几个相关的错误。

另外还有就是render.com上关联的repo忘记改了，需要关联新的仓库
