### ISSUE TITLE
Pages webpage shows old date?

### ISSUE THREAD

**Issue by zhangcs** [OpenCAEPlus/OpenCAEPoro#4]
### Describe the bug

Your site is live at https://opencaeplus.github.io/OpenCAEPoro/
Last [deployed](https://github.com/OpenCAEPlus/OpenCAEPoro/actions/runs/3255057520) by @[github-pages](https://github.com/apps/github-pages) github-pages 3 hours ago

But the webpage shows an old date (September). Seems not updated. 

### Reproduction

N/A

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Read the [docs](https://faspdevteam.github.io/OpenCAEPoro).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zhangcs** [comment]
Possibly the date is hard coded in the Doxygen config file.

**Comment by billcxx** [comment]
Will check tonight
