### ISSUE TITLE
CHANGELOG没有自动更新

### ISSUE THREAD

**Issue by zhangcs** [OpenCAEPlus/OpenCAEPoro#7]
### Describe the bug

增加一个新branch，然后merge，并没有改变CHANGELOG，这个文件好像一直都没有更新，是空的。

### Reproduction

Make a new branch, revise and merge. 

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Read the [docs](https://porous.opencaeplus.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by billcxx** [comment]
现在开branch然后merge不会更新release log和release信息

我们现在规定的自动化模式是这样的，都需要经过一个pull request的过程，比较正规的开源项目一般都是这样。较大的改动，像修正了bug，加了新功能最好都经过pull request，这样有比较完整的记录（从issue开始、讨论、到pr）。普通的小改动，像改改格式，改改typo，或者什么不希望写在release log里的可以直接commit到main上。

另外这样历史记录和讨论也都看起来比commit更方便，issue和pull request是开源软件很重要的一部分，因为新用户碰到一些问题会在这里搜索。

如果我们自己的闭源项目可以完全用trunk base dev的那种模式，但开源项目因为有外面的人也会加入，他们必须要用pull request，我感觉索性我们自己也这样就好了，只要保证每次branch的存货时间很短就好了。

## 现在更新release 和changelog是要这样做：

### Release
每次开pr然后merge，会更新release draft。注意要label这个pr为bug，enhancement还是doc，这样draft中它会自动归类。

### Changelog
changelog不是每次更新，它只在发布新release的时候更新，在release的时候github会自动生成一个名字叫“Release v.....”的pull request，这个pull request就会触发changelog更新的action

现在这个行为如果不适合我们的开发模式也可以调整成所有包含某个关键字的commit也会被触发release和changelog

**Comment by zhangcs** [comment]
Sounds good
